In [2]:
import numpy as np

In [3]:
l1=[1,2,3]
l2=[4,5,6]
print(l1+l2)

[1, 2, 3, 4, 5, 6]


In [6]:
n1=np.array(l1)
n2=np.array(l2)
print(n1+n2)


[5 7 9]


In [10]:
l=[1,2,3,'a']
arr=np.array(l)
print(arr)

['1' '2' '3' 'a']


In [12]:
l=[1,2,3.14,'a']
arr=np.array(l)
print(arr)

['1' '2' '3.14' 'a']


In [13]:
l=[1,2,3.14]
arr=np.array(l)
print(arr)

[1.   2.   3.14]


In [17]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
n=np.array(my_matrix)
print(n.shape)
#print(n[0][1:])
print(n)
print(n[:3,1:])

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]


In [22]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
n=np.array(my_matrix)
print(n.shape)
#print(n[0][1:])
print(n)
print(n[1:3,:2])

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5]
 [7 8]]


In [24]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
n=np.array(my_matrix)
print(n.shape)
#print(n[0][1:])
print(n)
print(n[1:,1:])

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]


In [26]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
n=np.array(my_matrix)
print(n.shape)
#print(n[0][1:])
print(n)
print(n[1:,:])

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]


In [35]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
n=np.array(my_matrix)
print(n.shape)
#print(n[0][1:])
print(n)
print(n[:2,0:2])

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


In [41]:
x=list(my_matrix)
print(type(x[0]))


<class 'list'>


In [43]:
n2=[1,2,3,4,5]
my_n2=np.array(n2)
my_n2_with_commas=my_n2.tolist()
print(my_n2_with_commas)
print(type(my_n2_with_commas))

[1, 2, 3, 4, 5]
<class 'list'>


In [45]:
np.arange(0,10) #it will create an array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [48]:
np.zeros(3)# it will create a single dimension array

array([0., 0., 0.])

In [50]:
np.zeros((5,5)) # it will create a matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
np.ones(3)

array([1., 1., 1.])

In [53]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [58]:
np.linspace(0,10,50)#single dimensional 

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [59]:
np.eye(4) # two dimensional

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
np.random.rand(2) #single dimensional 

array([0.34684899, 0.98554904])

In [64]:
np.random.rand(5,5)# two dimensional

array([[0.12878329, 0.99152095, 0.61972342, 0.11274879, 0.31465382],
       [0.44434027, 0.46297904, 0.21846063, 0.13030182, 0.23802191],
       [0.78444874, 0.32970198, 0.45508116, 0.6156189 , 0.86655905],
       [0.03324238, 0.80906095, 0.78478916, 0.78410114, 0.55189651],
       [0.456768  , 0.3164705 , 0.97062255, 0.55068006, 0.39949157]])

In [67]:
np.random.randint(1,100,size=(3,3))

array([[30, 96, 63],
       [17, 91, 82],
       [89, 47, 26]], dtype=int32)

In [69]:
np.random.randint(1,100,size=(5,5))

array([[61,  1, 79, 92, 84],
       [48, 64, 66, 96, 53],
       [94, 20, 79, 28, 15],
       [61, 17, 14, 37, 34],
       [62,  5,  9, 32, 72]], dtype=int32)

In [71]:
a=np.arange(0,10) #it will create an array
a[0:5]=100
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [84]:
a=np.array(([5,10,15],[20,25,30],[35,40,45]))
print(a[1])
print(a[1][0])
print(a[:2][1:])

a

[20 25 30]
20
[[20 25 30]]


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [86]:
np.log(a) 

array([[1.60943791, 2.30258509, 2.7080502 ],
       [2.99573227, 3.21887582, 3.40119738],
       [3.55534806, 3.68887945, 3.80666249]])

In [107]:
# 1d vector
# 2d matrix
# 3d is collection of 2d matrix
#4d is collection of 3d matrix
#5d is collection of 4d matrix

x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5)) # (no of matrix(dimensional))
x4=np.random.randint(10,size=(1,3,4,5))# (no of matrix(dimensional))
#print(x1)
# print(x2)
#print(x3)
print(x4)

[[[[7 4 0 8 3]
   [3 8 4 8 6]
   [8 6 0 4 4]
   [6 9 1 5 1]]

  [[3 9 2 7 6]
   [6 7 0 7 3]
   [2 7 8 0 8]
   [2 9 3 5 7]]

  [[5 4 9 9 9]
   [3 7 1 8 4]
   [8 2 9 9 8]
   [4 3 7 4 1]]]]


In [110]:
print("x1 ndim: ",x1.ndim)
print("x2 shape: ",x1.shape)
print("x3 size: ",x1.size) # size means no of elements


x1 ndim:  1
x2 shape:  (6,)
x3 size:  6


In [113]:
#x=np.concatenate([x1,x2])
grid=np.array([[1,2,3],[4,5,6]])

np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [116]:
np.concatenate([grid,grid],axis=1)#axis 1 means columns

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [117]:
np.concatenate([grid,grid],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [119]:
a=np.array([1,2,3,4,5,6])
c=np.where(a>2,a,999) #it's going by index
c

array([999, 999,   3,   4,   5,   6])

In [122]:
#isnan according to the none value if there is a value means false if it is not value means True
a=np.array([1,np.nan,3,np.nan])
r=np.isnan(a)
print(r)

[False  True False  True]


In [125]:
a=np.array([1,0,3,4,5,0])
print(np.any(a))
print(np.all(a))



True
False


In [127]:
a=np.array([1,1,3,4,5,1])
print(np.any(a))
print(np.all(a))


True
True


In [128]:
pip install pillow

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   --- ------------------------------------ 0.2/2.6 MB 7.0 MB/s eta 0:00:01
   --------- ------------------------------ 0.6/2.6 MB 7.5 MB/s eta 0:00:01
   --------------- ------------------------ 1.0/2.6 MB 8.1 MB/s eta 0:00:01
   ---------------------- ----------------- 1.5/2.6 MB 8.6 MB/s eta 0:00:01
   ----------------------------- ---------- 1.9/2.6 MB 8.8 MB/s eta 0:00:01
   ------------------------------------- -- 2.4/2.6 MB 9.1 MB/s eta 0:00:01
   ---------------------------------------  2.6/2.6 MB 9.3 MB/s eta 0:00:01
   ---------------------------------------  2.6/2.6 MB 9.3 MB/s eta 0:00:01
   ---------------------------------------- 2.6/2.6 MB 7.0 MB/s eta 0:00:00



[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [132]:
# Import the necessary libraries
from PIL import Image
from numpy import asarray


# load the image and convert into
# numpy array
img = Image.open('sample.png')

# asarray() class is used to convert
# PIL images into NumPy arrays
numpydata = asarray(img)

# <class 'numpy.ndarray'>
print(type(numpydata))

# shape
print(numpydata.shape)

print(numpydata)

<class 'numpy.ndarray'>
(316, 474, 3)
[[[114  92  69]
  [114  92  69]
  [114  92  69]
  ...
  [100  78  67]
  [100  78  67]
  [100  78  67]]

 [[114  92  69]
  [113  91  68]
  [112  90  67]
  ...
  [ 99  77  66]
  [ 99  77  66]
  [ 99  77  66]]

 [[113  91  68]
  [111  89  66]
  [109  87  66]
  ...
  [101  79  68]
  [ 98  76  65]
  [ 98  76  65]]

 ...

 [[157 123  98]
  [160 126 101]
  [139 107  82]
  ...
  [106  89  79]
  [ 89  75  64]
  [ 95  81  70]]

 [[145 111  86]
  [140 106  81]
  [131  99  74]
  ...
  [ 98  82  69]
  [ 97  83  70]
  [104  90  77]]

 [[151 117  92]
  [136 102  77]
  [132 100  75]
  ...
  [ 83  67  52]
  [ 98  84  71]
  [105  91  78]]]


In [134]:
from PIL import Image
import numpy as np

# Load image and convert to NumPy array
img = Image.open('sample.png')
img_array = np.array(img)
img.show()

In [136]:
# Calculate the grayscale value by averaging the RGB channels
gray_image = img_array.mean(axis=2).astype(np.uint8)

# Convert back to an image for viewing
gray_img = Image.fromarray(gray_image)
gray_img.show()  # This opens the grayscale image

In [138]:
# Horizontal flip
#flipped_horizontal = img_array[:, ::-1, :]

# Vertical flip
flipped_vertical = img_array[::-1, :, :]

# Show flipped images
#Image.fromarray(flipped_horizontal).show()  # Horizontal flip
Image.fromarray(flipped_vertical).show()    # Vertical flip

In [140]:
# Rotate image 90 degrees
rotated_image = np.rot90(img_array)

# Show the rotated image
Image.fromarray(rotated_image).show()

In [141]:
# Define a simple 3x3 mean filter
kernel = np.ones((3, 3)) / 9

# Pad the image to handle borders
padded_img = np.pad(img_array, ((1, 1), (1, 1), (0, 0)), mode='edge')

# Apply mean filter to each channel
blurred_img = np.zeros_like(img_array)
for channel in range(3):  # For each color channel
    for i in range(img_array.shape[0]):
        for j in range(img_array.shape[1]):
            blurred_img[i, j, channel] = (padded_img[i:i+3, j:j+3, channel] * kernel).sum()

# Show the blurred image
Image.fromarray(blurred_img).show()

In [142]:
# Convert to grayscale
gray_image = img_array.mean(axis=2).astype(np.uint8)

# Increase brightness
brightened_image = np.clip(gray_image * 1.3, 0, 255).astype(np.uint8)

# Horizontal flip
flipped_image = brightened_image[:, ::-1]

# Show the final processed image

Image.fromarray(flipped_image).show()

In [144]:
a=np.array([1,0,3,4,5,0])
print(np.any(a))
print(np.all(a))

True
False


In [146]:
a=np.array([1,np.nan,3,np.nan])
r=np.isnan(a)
print(r)

[False  True False  True]


In [148]:
a=np.random.randint(10,22,size=(3,4))
print(a)

[[13 18 20 13]
 [10 14 16 19]
 [13 21 19 11]]


In [151]:
z=np.zeros((5,5)) # it will create a matrix
np.fill_diagonal(z, np.arange(1, 6))
print(z)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [174]:
a=np.zeros((10,10))
a[:,[ 0,9]]=1
a[0:1,:]=1
a[9:10,:]=1

print(a)




[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [178]:
a=np.ones((10,10))
a[1:-1, 1:-1]=0
print(a)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [187]:
a=np.ones((10,10))
a[0:5, 0:5]=5
a[0:5, 5:]=6
a[5:, 0:5]=7
a[5:, 5:]=8
print(a)

[[5. 5. 5. 5. 5. 6. 6. 6. 6. 6.]
 [5. 5. 5. 5. 5. 6. 6. 6. 6. 6.]
 [5. 5. 5. 5. 5. 6. 6. 6. 6. 6.]
 [5. 5. 5. 5. 5. 6. 6. 6. 6. 6.]
 [5. 5. 5. 5. 5. 6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7. 8. 8. 8. 8. 8.]
 [7. 7. 7. 7. 7. 8. 8. 8. 8. 8.]
 [7. 7. 7. 7. 7. 8. 8. 8. 8. 8.]
 [7. 7. 7. 7. 7. 8. 8. 8. 8. 8.]
 [7. 7. 7. 7. 7. 8. 8. 8. 8. 8.]]


In [189]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import pandas as pd
s1=pd.Series([1,2,3,4],index=['USA','germany','USSR','Japan'])
s2=pd.Series([1,2,5,4],index=['USA','germany','Italy','Japan'])
print(s1+s2)
 

Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
germany    4.0
dtype: float64


In [202]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   ---------------------------------------  245.8/250.9 kB 7.4 MB/s eta 0:00:01
   ---------------------------------------  245.8/250.9 kB 7.4 MB/s eta 0:00:01
   ---------------------------------------- 250.9/250.9 kB 2.6 MB/s eta 0:00:00



[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [204]:
data=pd.read_excel('Book1.xlsx')
print(data.head)

<bound method NDFrame.head of   Unnamed: 0    City  Country  Maths  Science
0       John   Mumbai   India     42        6
1      Alice   London      UK     44       77
2        Bob   London      UK     43       59
3       Mary  Florida     USA     26       49
4        Dan   Madrid   Spain     82       58>


In [205]:
pd.read_excel('Book1.xlsx',index_col=0)

City  Country  Maths  Science
John    Mumbai   India     42        6
Alice   London      UK     44       77
Bob     London      UK     43       59
Mary   Florida     USA     26       49
Dan     Madrid   Spain     82       58

In [208]:
pd.read_excel("Book1.xlsx",index_col=0,usecols="A:C",names=['Name','City','Country'])

City Country
Name                  
John    Mumbai   India
Alice   London      UK
Bob     London      UK
Mary   Florida     USA
Dan     Madrid   Spain

In [210]:
pd.read_excel("Book1.xlsx",index_col=1,usecols="A:C",names=['Name','City','Country'])

Name Country
City                  
Mumbai    John   India
London   Alice      UK
London     Bob      UK
Florida   Mary     USA
Madrid     Dan   Spain

In [213]:
pd.read_excel("Book1.xlsx",index_col=0,usecols=[0,2,4]) #selecting the coloumns using usecols

Country  Science
John    India        6
Alice      UK       77
Bob        UK       59
Mary      USA       49
Dan     Spain       58

In [ ]:
pd.read_excel("Book1.xlsx",index_col=0,usecols=2) # you can't pass the directly valyue. Pass it as a index

ValueError: Passing an integer for `usecols` is no longer supported.  Please pass in a list of int from 0 to `usecols` inclusive instead.

In [220]:
pd.read_excel("Book1.xlsx",index_col=0,sheet_name=1)

City     Country Degree Specialization
Manish Sharma    Mumbai       India    MSC             Ma
M Chowdhury       Delhi       India    B.A            Phy
A Chow            Perth  Austrailia    PHD             Ma
David           Colombo   Sri Lanka    BBM        Parmacy
Samyaul Hridoy  Newyork         USA    BSC       Medicine

In [224]:
x=pd.read_excel("Book1.xlsx",index_col=0,sheet_name='teacher')
x

City     Country Degree Specialization
Manish Sharma    Mumbai       India    MSC             Ma
M Chowdhury       Delhi       India    B.A            Phy
A Chow            Perth  Austrailia    PHD             Ma
David           Colombo   Sri Lanka    BBM        Parmacy
Samyaul Hridoy  Newyork         USA    BSC       Medicine

In [232]:
x.head()
x.head(3)


City     Country Degree Specialization
Manish Sharma  Mumbai       India    MSC             Ma
M Chowdhury     Delhi       India    B.A            Phy
A Chow          Perth  Austrailia    PHD             Ma

In [230]:
x.tail()
x.tail(2)

City    Country Degree Specialization
David           Colombo  Sri Lanka    BBM        Parmacy
Samyaul Hridoy  Newyork        USA    BSC       Medicine

In [233]:
x.to_csv('teacher.csv')

In [3]:
data=pd.read_excel('Book2.xlsx',na_filter=False)
print(data)

    Country Age Salary Purchased
0    France  44  72000        No
1     Spain  27  48000       Yes
2   Germany  30  54000        No
3     Spain  38  61000        No
4   Germany  40              Yes
5    France  35  58000       Yes
6     Spain      52000        NO
7    France  48  79000       Yes
8   Germany  50  83000        No
9    France  37  67000       Yes
10   Indida      78000        No
11   Indida  28              Yes
12    Spain  36  56000       Yes
13   France  42  70000       Yes
14  Germany  50  86000        No
15    India  30  90000       Yes


In [239]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    16 non-null     object 
 1   Age        14 non-null     float64
 2   Salary     14 non-null     float64
 3   Purchased  16 non-null     object 
dtypes: float64(2), object(2)
memory usage: 644.0+ bytes


In [241]:
data.describe()# 5 point summary means describe

Age        Salary
count  14.000000     14.000000
mean   38.214286  68142.857143
std     7.875752  13643.015361
min    27.000000  48000.000000
25%    31.250000  56500.000000
50%    37.500000  68500.000000
75%    43.500000  78750.000000
max    50.000000  90000.000000

In [247]:
m=data['Age'].mean()
s=data['Salary'].mean()
print(s)
print(m)

68142.85714285714
38.214285714285715


In [249]:
print(data[4:8])
print(data.iloc[4:6])



   Country   Age   Salary Purchased
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        NO
7   France  48.0  79000.0       Yes
   Country   Age   Salary Purchased
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes


In [252]:
print(data['Country'][4])
print(data.Country[4])
print(data.iloc[4,0])
print(data.loc[4,'Country'])


Germany
Germany
Germany
Germany


In [257]:
print(data)
data=data.drop('Country',axis=1)#1=col 0=row
print(data)

     Age   Salary Purchased
0   44.0  72000.0        No
1   27.0  48000.0       Yes
2   30.0  54000.0        No
3   38.0  61000.0        No
4   40.0      NaN       Yes
5   35.0  58000.0       Yes
6    NaN  52000.0        NO
7   48.0  79000.0       Yes
8   50.0  83000.0        No
9   37.0  67000.0       Yes
10   NaN  78000.0        No
11  28.0      NaN       Yes
12  36.0  56000.0       Yes
13  42.0  70000.0       Yes
14  50.0  86000.0        No
15  30.0  90000.0       Yes


KeyError: "['Country'] not found in axis"

In [260]:
#ADDING C
data['Country']=['France','Spain','Germany','Spain','Germany','France','Spain','France','Germany','France','India','India','Spain','France','Germany','India']
data['Area']=['chennai','guindy']*8
print(data)

     Age   Salary Purchased  Country     Area
0   44.0  72000.0        No   France  chennai
1   27.0  48000.0       Yes    Spain   guindy
2   30.0  54000.0        No  Germany  chennai
3   38.0  61000.0        No    Spain   guindy
4   40.0      NaN       Yes  Germany  chennai
5   35.0  58000.0       Yes   France   guindy
6    NaN  52000.0        NO    Spain  chennai
7   48.0  79000.0       Yes   France   guindy
8   50.0  83000.0        No  Germany  chennai
9   37.0  67000.0       Yes   France   guindy
10   NaN  78000.0        No    India  chennai
11  28.0      NaN       Yes    India   guindy
12  36.0  56000.0       Yes    Spain  chennai
13  42.0  70000.0       Yes   France   guindy
14  50.0  86000.0        No  Germany  chennai
15  30.0  90000.0       Yes    India   guindy


In [262]:
data

Age   Salary Purchased  Country     Area
0   44.0  72000.0        No   France  chennai
1   27.0  48000.0       Yes    Spain   guindy
2   30.0  54000.0        No  Germany  chennai
3   38.0  61000.0        No    Spain   guindy
4   40.0      NaN       Yes  Germany  chennai
5   35.0  58000.0       Yes   France   guindy
6    NaN  52000.0        NO    Spain  chennai
7   48.0  79000.0       Yes   France   guindy
8   50.0  83000.0        No  Germany  chennai
9   37.0  67000.0       Yes   France   guindy
10   NaN  78000.0        No    India  chennai
11  28.0      NaN       Yes    India   guindy
12  36.0  56000.0       Yes    Spain  chennai
13  42.0  70000.0       Yes   France   guindy
14  50.0  86000.0        No  Germany  chennai
15  30.0  90000.0       Yes    India   guindy

In [265]:
print(data)
data=data.drop(3,axis=0)#to drop row give axis=0
data

     Age   Salary Purchased  Country     Area
0   44.0  72000.0        No   France  chennai
1   27.0  48000.0       Yes    Spain   guindy
2   30.0  54000.0        No  Germany  chennai
4   40.0      NaN       Yes  Germany  chennai
5   35.0  58000.0       Yes   France   guindy
6    NaN  52000.0        NO    Spain  chennai
7   48.0  79000.0       Yes   France   guindy
8   50.0  83000.0        No  Germany  chennai
9   37.0  67000.0       Yes   France   guindy
10   NaN  78000.0        No    India  chennai
11  28.0      NaN       Yes    India   guindy
12  36.0  56000.0       Yes    Spain  chennai
13  42.0  70000.0       Yes   France   guindy
14  50.0  86000.0        No  Germany  chennai
15  30.0  90000.0       Yes    India   guindy


KeyError: '[3] not found in axis'

In [267]:
print(data)
data2=data[5:8]
data=data.drop(5,axis=0)
data=data.drop(6,axis=0)
data=data.drop(7,axis=0)
print(data)
print(data2)


     Age   Salary Purchased  Country     Area
0   44.0  72000.0        No   France  chennai
1   27.0  48000.0       Yes    Spain   guindy
2   30.0  54000.0        No  Germany  chennai
4   40.0      NaN       Yes  Germany  chennai
5   35.0  58000.0       Yes   France   guindy
6    NaN  52000.0        NO    Spain  chennai
7   48.0  79000.0       Yes   France   guindy
8   50.0  83000.0        No  Germany  chennai
9   37.0  67000.0       Yes   France   guindy
10   NaN  78000.0        No    India  chennai
11  28.0      NaN       Yes    India   guindy
12  36.0  56000.0       Yes    Spain  chennai
13  42.0  70000.0       Yes   France   guindy
14  50.0  86000.0        No  Germany  chennai
15  30.0  90000.0       Yes    India   guindy
     Age   Salary Purchased  Country     Area
0   44.0  72000.0        No   France  chennai
1   27.0  48000.0       Yes    Spain   guindy
2   30.0  54000.0        No  Germany  chennai
4   40.0      NaN       Yes  Germany  chennai
8   50.0  83000.0        No  Germa

In [270]:
data1=data.sort_values(by='Salary',ascending=True)
data1

Age   Salary Purchased  Country     Area
1   27.0  48000.0       Yes    Spain   guindy
2   30.0  54000.0        No  Germany  chennai
12  36.0  56000.0       Yes    Spain  chennai
9   37.0  67000.0       Yes   France   guindy
13  42.0  70000.0       Yes   France   guindy
0   44.0  72000.0        No   France  chennai
10   NaN  78000.0        No    India  chennai
8   50.0  83000.0        No  Germany  chennai
14  50.0  86000.0        No  Germany  chennai
15  30.0  90000.0       Yes    India   guindy
4   40.0      NaN       Yes  Germany  chennai
11  28.0      NaN       Yes    India   guindy

In [272]:
print(data)
data.loc[data['Age']>40, 'Salary']=0

data

     Age   Salary Purchased  Country     Area
0   44.0      0.0        No   France  chennai
1   27.0  48000.0       Yes    Spain   guindy
2   30.0  54000.0        No  Germany  chennai
4   40.0      NaN       Yes  Germany  chennai
8   50.0      0.0        No  Germany  chennai
9   37.0  67000.0       Yes   France   guindy
10   NaN  78000.0        No    India  chennai
11  28.0      NaN       Yes    India   guindy
12  36.0  56000.0       Yes    Spain  chennai
13  42.0      0.0       Yes   France   guindy
14  50.0      0.0        No  Germany  chennai
15  30.0  90000.0       Yes    India   guindy


Age   Salary Purchased  Country     Area
0   44.0      0.0        No   France  chennai
1   27.0  48000.0       Yes    Spain   guindy
2   30.0  54000.0        No  Germany  chennai
4   40.0      NaN       Yes  Germany  chennai
8   50.0      0.0        No  Germany  chennai
9   37.0  67000.0       Yes   France   guindy
10   NaN  78000.0        No    India  chennai
11  28.0      NaN       Yes    India   guindy
12  36.0  56000.0       Yes    Spain  chennai
13  42.0      0.0       Yes   France   guindy
14  50.0      0.0        No  Germany  chennai
15  30.0  90000.0       Yes    India   guindy

In [275]:
print(data)
data.loc[((data['Age']>20) & (data['Country']=='Germany')),'Salary']=0
data

     Age   Salary Purchased  Country     Area
0   44.0      0.0        No   France  chennai
1   27.0  48000.0       Yes    Spain   guindy
2   30.0      0.0        No  Germany  chennai
4   40.0      0.0       Yes  Germany  chennai
8   50.0      0.0        No  Germany  chennai
9   37.0  67000.0       Yes   France   guindy
10   NaN  78000.0        No    India  chennai
11  28.0      NaN       Yes    India   guindy
12  36.0  56000.0       Yes    Spain  chennai
13  42.0      0.0       Yes   France   guindy
14  50.0      0.0        No  Germany  chennai
15  30.0  90000.0       Yes    India   guindy


Age   Salary Purchased  Country     Area
0   44.0      0.0        No   France  chennai
1   27.0  48000.0       Yes    Spain   guindy
2   30.0      0.0        No  Germany  chennai
4   40.0      0.0       Yes  Germany  chennai
8   50.0      0.0        No  Germany  chennai
9   37.0  67000.0       Yes   France   guindy
10   NaN  78000.0        No    India  chennai
11  28.0      NaN       Yes    India   guindy
12  36.0  56000.0       Yes    Spain  chennai
13  42.0      0.0       Yes   France   guindy
14  50.0      0.0        No  Germany  chennai
15  30.0  90000.0       Yes    India   guindy

In [277]:
print(data)
data.loc[((data['Age']>20) & (data['Country']=='Spain')),['Salary','Age']]=0
data

     Age   Salary Purchased  Country     Area
0   44.0      0.0        No   France  chennai
1    0.0      0.0       Yes    Spain   guindy
2   30.0      0.0        No  Germany  chennai
4   40.0      0.0       Yes  Germany  chennai
8   50.0      0.0        No  Germany  chennai
9   37.0  67000.0       Yes   France   guindy
10   NaN  78000.0        No    India  chennai
11  28.0      NaN       Yes    India   guindy
12   0.0      0.0       Yes    Spain  chennai
13  42.0      0.0       Yes   France   guindy
14  50.0      0.0        No  Germany  chennai
15  30.0  90000.0       Yes    India   guindy


Age   Salary Purchased  Country     Area
0   44.0      0.0        No   France  chennai
1    0.0      0.0       Yes    Spain   guindy
2   30.0      0.0        No  Germany  chennai
4   40.0      0.0       Yes  Germany  chennai
8   50.0      0.0        No  Germany  chennai
9   37.0  67000.0       Yes   France   guindy
10   NaN  78000.0        No    India  chennai
11  28.0      NaN       Yes    India   guindy
12   0.0      0.0       Yes    Spain  chennai
13  42.0      0.0       Yes   France   guindy
14  50.0      0.0        No  Germany  chennai
15  30.0  90000.0       Yes    India   guindy

In [5]:
data=pd.read_csv('teacher.csv')
print(data)

       Unnamed: 0     City     Country Degree Specialization
0   Manish Sharma   Mumbai       India    MSC             Ma
1     M Chowdhury    Delhi       India    B.A            Phy
2          A Chow    Perth  Austrailia    PHD             Ma
3           David  Colombo   Sri Lanka    BBM        Parmacy
4  Samyaul Hridoy  Newyork         USA    BSC       Medicine


In [4]:
df=pd.read_json('book.json')
print(df)

ValueError: Expected object or value

In [7]:
data=pd.read_excel('Book2.xlsx')
print(data)

    Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
4   Germany  40.0      NaN       Yes
..      ...   ...      ...       ...
94   France  42.0  70000.0       Yes
95  Germany  50.0  86000.0        No
96    India  30.0  90000.0       Yes
97   France  42.0  70000.0       Yes
98  Germany  50.0  83000.0        No

[99 rows x 4 columns]


In [10]:
sample_data=data.sample(n=3)
sample_data


Country   Age   Salary Purchased
85   India  30.0  90000.0       Yes
66   Spain  36.0  56000.0       Yes
59  France  35.0  58000.0       Yes

In [15]:
sample_data=data.sample(frac=.25)
len(sample_data)


25

In [25]:
sample_data=data.sample( frac=.10,random_state=5)
sample_data

Country   Age   Salary Purchased
66    Spain  36.0  56000.0       Yes
32   France  35.0  58000.0       Yes
46    Spain  38.0  61000.0        No
28    Spain  36.0  56000.0       Yes
74  Germany  40.0      NaN       Yes
23   France  48.0  79000.0       Yes
10   Indida   NaN  78000.0        No
20  Germany  40.0      NaN       Yes
17    Spain  27.0  48000.0       Yes
35  Germany  50.0  83000.0        No

In [54]:
sample_data=data.sample(n=1,axis=1) #to randomly pick a column n=1,axis=1
sample_data

Age
0   44.0
1   27.0
2   30.0
3   38.0
4   40.0
..   ...
94  42.0
95  50.0
96  30.0
97  42.0
98  50.0

[99 rows x 1 columns]

In [306]:
import random 

computer_data=['rock','paper','scissors']
u=0
c=0

#print(computer)
def game(user):
    global u,c
    
    computer=random.choice(computer_data)
    if user==computer:
        pass
    elif user=='rock' and computer=='scissors':
        u=u+1
        #print("User Wins!",user)
    elif user=='rock' and computer=='paper':
            c=c+1
            #print("Computer Wins!",computer)
    elif user=='paper' and computer=='scissors':
            c=c+1
            #print("Computer Wins!",computer)
    elif user=='paper' and computer=='rock':
            u=u+1
            #print("User Wins!",user)
    elif user=='scissors' and computer=='rock':
            c=c+1
            #print("Computer Wins!")
    elif user=='scissors' and computer=='paper':
            u=u+1
            #print("User Wins!",user)
        

for i in range(5):
    o=game(input())
if u>c:
    print(f"User Score:{u} Computer score: {c}")
    print("USER WINS!")
else:
    print(f"User Score:{u} Computer score: {c}")
    print("Computer Wins!")


User Score:1 Computer score: 3
Computer Wins!


In [307]:
import mysql.connector

mydb=mysql.connector.connect(
    host='localhost',
    user='root',
    password='root@39'
)
mycursor=mydb.cursor() #It wil navigate to my sql workbench
mycursor.execute('CREATE DATABASE Game') # to use any sql query's use execute

In [308]:
mydb=mysql.connector.connect(
    host='localhost',
    user='root',
    password='root@39',
    database='Game'
)
mycursor=mydb.cursor() #It wil navigate to my sql workbench
mycursor.execute('CREATE TABLE game_datas (User_data VARCHAR(225),Computer_data VARCHAR(225))') # creating a table using execute
print('table created')

table created


In [309]:
import mysql.connector
import random 

computer_data=['rock','paper','scissors']
u=0
c=0

#print(computer)
def game(user):
    global u,c
    def __init__(self):
            self.mydb=mysql.connector.connect(
            host='localhost',
            user='root',
            password='root@39',
            database='supermarket'

        )
            self.mycursor=self.mydb.cursor()
            print("connected")
    computer=random.choice(computer_data)
    if user==computer:
        pass
    elif user=='rock' and computer=='scissors':
        u=u+1
        #print("User Wins!",user)
    elif user=='rock' and computer=='paper':
            c=c+1
            #print("Computer Wins!",computer)
    elif user=='paper' and computer=='scissors':
            c=c+1
            #print("Computer Wins!",computer)
    elif user=='paper' and computer=='rock':
            u=u+1
            #print("User Wins!",user)
    elif user=='scissors' and computer=='rock':
            c=c+1
            #print("Computer Wins!")
    elif user=='scissors' and computer=='paper':
            u=u+1
            #print("User Wins!",user)
        

for i in range(5):
    o=game(input())
if u>c:
    print(f"User Score:{u} Computer score: {c}")
    print("USER WINS!")
else:
    print(f"User Score:{u} Computer score: {c}")
    print("Computer Wins!")


User Score:1 Computer score: 2
Computer Wins!


In [314]:
for i in range(0,100,2):
    if i==0:
        continue
    print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98


In [316]:
n1=int(input())
n2=int(input())
x=n1+n2
c=x-n1-n2
c

0